/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated.users'
import { Route as AuthenticatedTimetablesRouteImport } from './routes/_authenticated.timetables'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated.students'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedPrintRouteImport } from './routes/_authenticated.print'
import { Route as AuthenticatedPredictorRouteImport } from './routes/_authenticated.predictor'
import { Route as AuthenticatedLessonPlannerRouteImport } from './routes/_authenticated.lesson-planner'
import { Route as AuthenticatedLeavesRouteImport } from './routes/_authenticated.leaves'
import { Route as AuthenticatedFacilitiesRouteImport } from './routes/_authenticated.facilities'
import { Route as AuthenticatedCircularsRouteImport } from './routes/_authenticated.circulars'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated.chat'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated.attendance'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated.students.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTimetablesRoute = AuthenticatedTimetablesRouteImport.update({
  id: '/timetables',
  path: '/timetables',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrintRoute = AuthenticatedPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPredictorRoute = AuthenticatedPredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLessonPlannerRoute =
  AuthenticatedLessonPlannerRouteImport.update({
    id: '/lesson-planner',
    path: '/lesson-planner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeavesRoute = AuthenticatedLeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFacilitiesRoute = AuthenticatedFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCircularsRoute = AuthenticatedCircularsRouteImport.update({
  id: '/circulars',
  path: '/circulars',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedStudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/chat': typeof AuthenticatedChatRoute
  '/circulars': typeof AuthenticatedCircularsRoute
  '/facilities': typeof AuthenticatedFacilitiesRoute
  '/leaves': typeof AuthenticatedLeavesRoute
  '/lesson-planner': typeof AuthenticatedLessonPlannerRoute
  '/predictor': typeof AuthenticatedPredictorRoute
  '/print': typeof AuthenticatedPrintRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/timetables': typeof AuthenticatedTimetablesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/chat': typeof AuthenticatedChatRoute
  '/circulars': typeof AuthenticatedCircularsRoute
  '/facilities': typeof AuthenticatedFacilitiesRoute
  '/leaves': typeof AuthenticatedLeavesRoute
  '/lesson-planner': typeof AuthenticatedLessonPlannerRoute
  '/predictor': typeof AuthenticatedPredictorRoute
  '/print': typeof AuthenticatedPrintRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRouteWithChildren
  '/timetables': typeof AuthenticatedTimetablesRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/circulars': typeof AuthenticatedCircularsRoute
  '/_authenticated/facilities': typeof AuthenticatedFacilitiesRoute
  '/_authenticated/leaves': typeof AuthenticatedLeavesRoute
  '/_authenticated/lesson-planner': typeof AuthenticatedLessonPlannerRoute
  '/_authenticated/predictor': typeof AuthenticatedPredictorRoute
  '/_authenticated/print': typeof AuthenticatedPrintRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRouteWithChildren
  '/_authenticated/timetables': typeof AuthenticatedTimetablesRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/attendance'
    | '/chat'
    | '/circulars'
    | '/facilities'
    | '/leaves'
    | '/lesson-planner'
    | '/predictor'
    | '/print'
    | '/reports'
    | '/settings'
    | '/students'
    | '/timetables'
    | '/users'
    | '/students/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/attendance'
    | '/chat'
    | '/circulars'
    | '/facilities'
    | '/leaves'
    | '/lesson-planner'
    | '/predictor'
    | '/print'
    | '/reports'
    | '/settings'
    | '/students'
    | '/timetables'
    | '/users'
    | '/'
    | '/students/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/attendance'
    | '/_authenticated/chat'
    | '/_authenticated/circulars'
    | '/_authenticated/facilities'
    | '/_authenticated/leaves'
    | '/_authenticated/lesson-planner'
    | '/_authenticated/predictor'
    | '/_authenticated/print'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/students'
    | '/_authenticated/timetables'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/students/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/timetables': {
      id: '/_authenticated/timetables'
      path: '/timetables'
      fullPath: '/timetables'
      preLoaderRoute: typeof AuthenticatedTimetablesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/print': {
      id: '/_authenticated/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof AuthenticatedPrintRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/predictor': {
      id: '/_authenticated/predictor'
      path: '/predictor'
      fullPath: '/predictor'
      preLoaderRoute: typeof AuthenticatedPredictorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lesson-planner': {
      id: '/_authenticated/lesson-planner'
      path: '/lesson-planner'
      fullPath: '/lesson-planner'
      preLoaderRoute: typeof AuthenticatedLessonPlannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaves': {
      id: '/_authenticated/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof AuthenticatedLeavesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facilities': {
      id: '/_authenticated/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof AuthenticatedFacilitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/circulars': {
      id: '/_authenticated/circulars'
      path: '/circulars'
      fullPath: '/circulars'
      preLoaderRoute: typeof AuthenticatedCircularsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedStudentsRoute
    }
  }
}

interface AuthenticatedStudentsRouteChildren {
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
}

const AuthenticatedStudentsRouteChildren: AuthenticatedStudentsRouteChildren = {
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
}

const AuthenticatedStudentsRouteWithChildren =
  AuthenticatedStudentsRoute._addFileChildren(
    AuthenticatedStudentsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCircularsRoute: typeof AuthenticatedCircularsRoute
  AuthenticatedFacilitiesRoute: typeof AuthenticatedFacilitiesRoute
  AuthenticatedLeavesRoute: typeof AuthenticatedLeavesRoute
  AuthenticatedLessonPlannerRoute: typeof AuthenticatedLessonPlannerRoute
  AuthenticatedPredictorRoute: typeof AuthenticatedPredictorRoute
  AuthenticatedPrintRoute: typeof AuthenticatedPrintRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRouteWithChildren
  AuthenticatedTimetablesRoute: typeof AuthenticatedTimetablesRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCircularsRoute: AuthenticatedCircularsRoute,
  AuthenticatedFacilitiesRoute: AuthenticatedFacilitiesRoute,
  AuthenticatedLeavesRoute: AuthenticatedLeavesRoute,
  AuthenticatedLessonPlannerRoute: AuthenticatedLessonPlannerRoute,
  AuthenticatedPredictorRoute: AuthenticatedPredictorRoute,
  AuthenticatedPrintRoute: AuthenticatedPrintRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRouteWithChildren,
  AuthenticatedTimetablesRoute: AuthenticatedTimetablesRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
